### ISSUE TITLE
[build] version: 20v6

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-pluto#175]
# Issues: 
- [x] remove backfill and remove `dcp_pluto` and `dcp_mappluto` from dataloading #179
- [x] refactor dataloading for `pluto_input_research` using the [same process](https://github.com/NYCPlanning/db-developments/blob/4e7fe31823c70db8c50a55527b5288c316c14f40/developments_build/config.sh#L63-L65) as `db-developments`, this should be done for all used tables in the `data` folder --> also note that this could have downward impact on preprocessing.sql. #178 
- [x] manually recreate the view for `pluto_pts` in `RECIPE_ENGINE` only selecting a filtered subset of columns #176 

# Data loading
- [x] **dcp_edesignation** (updated with zoning features)
- [ ] **dcas_facilities_colp** (updated twice a year)
- [x] **lpc_historic_districts** (check date [here](https://data.cityofnewyork.us/Housing-Development/LPC-Individual-Landmark-and-Historic-District-Buil/7mgd-s57w))
- [x] **lpc_landmarks** (check date [here](https://data.cityofnewyork.us/Housing-Development/Designated-and-Calendared-Buildings-and-Sites-Map-/jcj6-zji6)
> for spatial joins. Check [Bytes](https://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page) for the spatial boundaries
- [x] **dcp_cdboundaries** (update to 20c)
- [x] **dcp_censustracts** (update to 20c)
- [x] **dcp_censusblocks** (update to 20c)
- [x] **dcp_school_districts** (update to 20c)
- [x] **dcp_councildistricts**  (update to 20c)
- [x] **doitt_zipcodeboundaries** (almost never updated, check [here](https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u))
- [x] **dcp_firecompanies**  (update to 20c)
- [x] **dcp_policeprecincts**  (update to 20c)
- [x] **dcp_healthareas**  (update to 20c)
- [x] **dcp_healthcenters**  (update to 20c)
- [x] **dsny_frequencies** (**frequent** updates, check [here](https://data.cityofnewyork.us/City-Government/DSNY-Frequencies/gyhq-r8du))
- [ ] **dpr_greenthumb** (Not sure where this data set is coming from at this moment)
> other_datasets 
- [x] **dof_dtm** (updated when generating Zoning tax lots, ignore)
- [x] **dof_shoreline** (updated when generating Zoning tax lots, ignore)
- [x] **dof_condo** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_commercialoverlay** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_limitedheight** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningdistricts** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_specialpurpose** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_specialpurposesubdistricts** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningmapamendments** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningmapindex** (never updated, safe to ignore)
- [x] **fema_firms2007_100yr** (never updated, safe to ignore)
- [x] **fema_pfirms2015_100yr** (never updated, safe to ignore)
> computed
- [x] **pluto_corrections** (pulling from bytes, must update)
- [ ] **pluto_input_research** (depends on if there's new research, must update)
- [x] **pluto_input_numbldgs** (computed when building footprints are updated, check [here](https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh))
- [x] **pluto_pts** (pulled from SFTP)
- [x] **pluto_input_geocodes** (Generated with pts)
- [x] **pluto_input_cama_dof** (pulled from SFTP)
# PLUTO Improvements (corrections)

# Comments

**Comment by SPTKL** [comment]
[build] first build, confirming all source data loaded

**Comment by SPTKL** [comment]
[build]

**Comment by mgraber** [comment]
[build]

**Comment by SPTKL** [comment]
[build] with updated dcp_censustracts ( wrong source srs)

**Comment by SPTKL** [comment]
published
