### ISSUE TITLE
[build] version: 20v7

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-pluto#187]
Rebuild 20v6 using DTM that hasn't had RepairGeometry applied. It is in recipes under version `dof_dtm.2020/09/14_raw`

# Data loading
- [x] **dcp_edesignation** (updated with zoning features)
- [x] **dcas_facilities_colp** (updated twice a year)
- [x] **lpc_historic_districts** (check date [here](https://data.cityofnewyork.us/Housing-Development/LPC-Individual-Landmark-and-Historic-District-Buil/7mgd-s57w))
- [x] **lpc_landmarks** (check date [here](https://data.cityofnewyork.us/Housing-Development/Designated-and-Calendared-Buildings-and-Sites-Map-/jcj6-zji6)
> for spatial joins. Check [Bytes](https://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page) for the spatial boundaries
- [x] **dcp_cdboundaries** (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_censustracts** (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_censusblocks** (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_school_districts**  (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_councildistricts**  (updated quaterly, 19d, 20a e.g.)
- [x] **doitt_zipcodeboundaries** (almost never updated, check [here](https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u))
- [x] **dcp_firecompanies**  (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_policeprecincts**  (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_healthareas**  (updated quaterly, 19d, 20a e.g.)
- [x] **dcp_healthcenters**  (updated quaterly, 19d, 20a e.g.)
- [x] **dsny_frequencies** (**frequent** updates, check [here](https://data.cityofnewyork.us/City-Government/DSNY-Frequencies/gyhq-r8du))
- [x] **dpr_greenthumb** (Not sure where this data set is coming from at this momment)
> other_datasets 
- [x] **dof_dtm** (updated when generating Zoning tax lots, ignore)
- [x] **dof_shoreline** (updated when generating Zoning tax lots, ignore)
- [x] **dof_condo** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_commercialoverlay** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_limitedheight** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningdistricts** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_specialpurpose** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_specialpurposesubdistricts** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningmapamendments** (updated when generating Zoning tax lots, ignore)
- [x] **dcp_zoningmapindex** (never updated, safe to ignore)
- [x] **fema_firms2007_100yr** (never updated, safe to ignore)
- [x] **fema_pfirms2015_100yr** (never updated, safe to ignore)
> computed
- [ ] **pluto_corrections** (pulling from bytes, must update in recipes)
- [x] **pluto_input_research** (just update the file in repo, no need to push to recipes)
- [x] **pluto_input_numbldgs** (computed when building footprints are updated, check [here](https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh))
- [x] **pluto_pts** (pulled from SFTP) #194 
- [x] **pluto_input_geocodes** (Generated with pts) #194 
- [x] **pluto_input_cama_dof** (pulled from SFTP) #193 
# PLUTO Improvements (corrections)

# Comments

**Comment by mgraber** [comment]
[build]

**Comment by mgraber** [comment]
[build]

**Comment by mgraber** [comment]
[build] again after merging #190

**Comment by SPTKL** [comment]
[build]
